//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanAn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_power_off_on_shutdown_512 {
            get {
                object obj = ResourceManager.GetObject("1_power-off-on-shutdown-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12249875316766 {
            get {
                object obj = ResourceManager.GetObject("12249875316766", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32393_pot_of_food_icon {
            get {
                object obj = ResourceManager.GetObject("32393-pot-of-food-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_1520315779_width650height488 {
            get {
                object obj = ResourceManager.GetObject("5-1520315779-width650height488", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7up_sleek_330ml_2_700x467_1 {
            get {
                object obj = ResourceManager.GetObject("7up-sleek-330ml-2-700x467-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bia_tiger_lon_01 {
            get {
                object obj = ResourceManager.GetObject("bia-tiger-lon-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BiaHeineken {
            get {
                object obj = ResourceManager.GetObject("BiaHeineken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer {
            get {
                object obj = ResourceManager.GetObject("customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap door_exit {
            get {
                object obj = ResourceManager.GetObject("door_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DpyRQk5VAAEhhSc {
            get {
                object obj = ResourceManager.GetObject("DpyRQk5VAAEhhSc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giu_trai_cay_tuoi_5_2017 {
            get {
                object obj = ResourceManager.GetObject("giu-trai-cay-tuoi-5-2017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goi_sua_vietstreet {
            get {
                object obj = ResourceManager.GetObject("goi_sua_vietstreet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goi_tom_queen {
            get {
                object obj = ResourceManager.GetObject("goi_tom_queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hinhanhmonngonvietnam111 {
            get {
                object obj = ResourceManager.GetObject("hinhanhmonngonvietnam111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_profile_avatar_icon_5b3899483fa7a8_4711163815304359122607 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-profile-avatar-icon-5b3899483fa7a8.471116381530435912" +
                        "2607", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_juice_puzzle_drink_drink_png_photos_5a77a916438b86_1144186515177915102767 {
            get {
                object obj = ResourceManager.GetObject("kisspng-juice-puzzle-drink-drink-png-photos-5a77a916438b86.1144186515177915102767" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mon_che_ngon_de_kinh_doanh {
            get {
                object obj = ResourceManager.GetObject("mon-che-ngon-de-kinh-doanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ngo_chien_queenhotel {
            get {
                object obj = ResourceManager.GetObject("ngo_chien_queenhotel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_ngot_coke_sleek_330ml_1_700x467_1 {
            get {
                object obj = ResourceManager.GetObject("nuoc-ngot-coke-sleek-330ml-1-700x467-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_ngot_fanta_vi_cam_lon_330ml_201812281420358633 {
            get {
                object obj = ResourceManager.GetObject("nuoc-ngot-fanta-vi-cam-lon-330ml-201812281420358633", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuoc_tang_luc_sting_dau_sleek_lon_330ml_1_700x467_1 {
            get {
                object obj = ResourceManager.GetObject("nuoc-tang-luc-sting-dau-sleek-lon-330ml-1-700x467-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saymevoi20montrangmiengtrudanhcuay6 {
            get {
                object obj = ResourceManager.GetObject("saymevoi20montrangmiengtrudanhcuay6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap staff {
            get {
                object obj = ResourceManager.GetObject("staff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sup_queen_hotel {
            get {
                object obj = ResourceManager.GetObject("Sup_queen_hotel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thung_nuoc_khoang_lavie_750ml_4853 {
            get {
                object obj = ResourceManager.GetObject("thung-nuoc-khoang-lavie-750ml-4853", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_1 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_10 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_11 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_12 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_13 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_2 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_3 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_4 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_5 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_6 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_7 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_8 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_81 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_9 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_15_hinh_anh_mon_an_ngon_viet_nam_khien_ban_khong_the_roi_mat_91 {
            get {
                object obj = ResourceManager.GetObject("top-15-hinh-anh-mon-an-ngon-viet-nam-khien-ban-khong-the-roi-mat-91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_food_clipart_10 {
            get {
                object obj = ResourceManager.GetObject("transparent-food-clipart-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
